#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Mono.Samples.Notepad.Resource", IsApplication=true)]

namespace Mono.Samples.Notepad
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int imp_levels = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_looks_3_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_looks_one_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_looks_two_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_search = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int add = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int body = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int cancel = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int description = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int icon = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int level = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int modified = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int save = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int search = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int NoteEditor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NoteListRow = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int options_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu_delete = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_insert = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int menu_search = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int search_hint = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int search_label = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int settings_description = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
